spring:
  application:
    name: user
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 6379
    pool.max-idle: 8
    pool.min-idle: 0
    pool.max-active: 8
    pool.max-wait: -1
    timeout: 5000
server:
  port: 7000
ribbon:
  eureka:
    enabled: true
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:1111/eureka/
---
spring:
  profiles: dev
  redis:
    host: 172.19.178.227
    port: 6379
    password: redis
eureka.client.serviceUrl.defaultZone: http://172.19.178.227:1111/eureka/