spring:
  application:
    name: eureka
server:
  port: 8000
  contextPath:
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${server.port:8000}:${server.contextPath}/eureka/
---
spring.profiles: dev