spring:
  application:
    name: eureka
server:
  port: 1111
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
    ipAddress: 47.101.45.123
    nonSecurePort: 80
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 90
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${server.port:1111}${server.contextPath}/eureka/