server:
  port: 8003
spring:
  application:
    name: sy-feign
  redis:
    host: localhost
    port: 6379
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/
---
spring:
  profiles: dev
  redis:
    host: localhost
    port: 6379
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8000/eureka/