spring:
  application:
    name: feign
server:
  port: 7002
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:1111/eureka/
-----
spring:
  profiles: dev
  redis:
    host: 172.19.178.227
    port: 6379
    password: redis
eureka.client.serviceUrl.defaultZone: http://172.19.178.227:1111/eureka/